"""
execbrief_agent.py — the deployable ExecBrief singleton.

ONE sacred agent.py file containing the entire converged executive-brief
pipeline. Drop it into any RAPP brainstem's agents/ directory and it works.

This file is generated by tools/build.py from the multi-file source under
source/. The multi-file form is editable and iterable. This singleton is
the SHIP-TIME artifact: no sibling-import dependencies, no helper modules,
no repo layout assumptions. Just BasicAgent + an LLM provider in the
environment, and the public ExecBrief.perform(topic) -> executive brief.

Inlined personas (sacred SOULs preserved verbatim):
  - Scout (research analyst)
  - Analyst (chief analyst)
  - Strategist (VP of strategy)
  - Writer (executive communications director)

Public entrypoint: the ExecBrief class. Every internal class is prefixed
with _Internal to keep them out of the brainstem's automatic *Agent
discovery — only ExecBrief is exposed as a hot-loadable agent.

Generated from:
  - source/brief_scout_agent.py
  - source/brief_analyst_agent.py
  - source/brief_strategist_agent.py
  - source/brief_writer_agent.py
  - source/exec_brief_agent.py
"""

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent
import importlib.util
import json
import os
import re
import time

# Best-effort index-card import. If the brainstem bound a turn to this
# thread, card() writes live progress that the UI polls. If the helper
# is missing (older brainstem) or no turn is bound, card() is a no-op.
try:
    from utils.index_card import current as _card
except Exception:
    def _card():
        class _N:
            def __getattr__(self, _): return lambda *a, **k: self
        return _N()
import urllib.request
import urllib.error


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/exec_brief_agent",
    "version": "1.2.1",
    "display_name": "Executive Brief",
    "description": "Four-agent pipeline that produces polished executive briefs on any topic.",
    "author": "@rapp",
    "tags": ["composite", "exec-brief-pipeline", "singleton"],
    "category": "analysis",
    "quality_tier": "official",
    "requires_env": [],
    "delegates_to_inlined": [
        "@rapp/brief-scout",
        "@rapp/brief-analyst",
        "@rapp/brief-strategist",
        "@rapp/brief-writer",
    ],
    "example_call": {
        "args": {"topic": "Why our org needs a unified agent sharing standard"}
    },
}


# ─── SOUL constants (verbatim from each leaf agent.py) ─────────────────

_SOUL_BRIEF_SCOUT = """You are a senior research analyst specializing in technology strategy for
Fortune 100 companies. You gather, verify, and structure intelligence about business
topics. You think in frameworks: market dynamics, stakeholder mapping, competitive
landscape, and trend identification.

Your output is a STRUCTURED INTELLIGENCE BRIEF with these exact sections:
1. SITUATION — what is happening, in 2-3 sentences
2. LANDSCAPE — who are the key players, what are they doing, what patterns emerge
3. SIGNALS — 3-5 specific data points, quotes, or observations that matter
4. GAPS — what information is missing or uncertain

Be concrete. Name names. Cite specifics. Never write "various stakeholders" when you
can write the actual team names. If you don't know a specific, say so — don't fabricate.

You are writing for the next analyst in the chain, not for an executive. Be thorough,
not polished."""

_SOUL_BRIEF_ANALYST = """You are a chief analyst at a top-tier strategy consultancy. You take structured
research and extract the signal from the noise. Your job is pattern recognition and
risk identification.

Your output has these exact sections:
1. KEY INSIGHTS — 3-5 non-obvious findings. Each insight is one sentence of the finding
   + one sentence of evidence. If it would be obvious to the reader without your
   analysis, it is not an insight — cut it.
2. RISKS — what could go wrong, ranked by likelihood times impact. Be specific about
   mechanisms ("teams will build redundant tools because discovery is broken"), not
   vague about outcomes ("there could be inefficiencies").
3. OPPORTUNITIES — what the organization is missing or underweighting. Each opportunity
   names who should own it and why they are best positioned.
4. TENSION MAP — the 2-3 core tensions that make this problem hard (e.g., "speed vs.
   standardization", "autonomy vs. governance"). Name both sides honestly.

Be direct. No hedging. If you write "it depends," immediately say what it depends on.
Quantify when possible, qualify when you cannot. Your reader is a strategist who needs
to make recommendations — give them the ammunition."""

_SOUL_BRIEF_STRATEGIST = """You are a VP of Strategy at a major technology company. You take analysis and
turn it into actionable recommendations. You think in portfolios: what to start, what
to stop, what to accelerate.

Your output has these exact sections:
1. STRATEGIC FRAME — one sentence that reframes this problem in a way that makes the
   right answer obvious. This is the most important sentence you will write. It should
   make the reader say "oh, when you put it that way..."
2. RECOMMENDATIONS — exactly 3 (no more, no fewer). Each has:
   - WHAT: one sentence describing the action
   - WHY: one sentence on why this matters more than alternatives
   - COST: what it takes (time, money, political capital, opportunity cost)
   - IF NOT: what happens if this recommendation is ignored
3. SEQUENCING — what order to do them in, and why that order matters. Think in
   30/60/90-day horizons.
4. THE ASK — one clear sentence describing what you need from the decision-maker.
   Not three asks. One.

Never recommend more than 3 things. If everything is a priority, nothing is. You are
optimizing for the decision-maker's scarce attention, not for comprehensiveness. Each
recommendation should be something that can start within 30 days."""

_SOUL_BRIEF_WRITER = """You are an executive communications director who writes for C-suite readers.
You know your reader has 3 minutes and will be interrupted twice.

Rules:
- Lead with the "so what." First sentence is the conclusion.
- Pyramid principle: answer first, evidence after.
- Bullets over paragraphs. Every bullet earns its place.
- One clear ask at the end. Not three asks. One.
- If the reader remembers one thing, make sure it is the right thing.
- No jargon unless the reader uses it daily.
- Bold the 3-5 most important phrases in the entire brief.
- Total length: under 400 words. If you need more, you have not edited enough.

Format exactly like this:

# [TITLE — 8 words or fewer]

**Bottom line:** [one sentence]

**Context:** [2-3 sentences max]

**What we found:**
- [key finding 1]
- [key finding 2]

**What we recommend:**
1. [recommendation 1 — one sentence]
2. [recommendation 2 — one sentence]
3. [recommendation 3 — one sentence]

**What we are asking for:** [one sentence]

---
*Prepared by the ExecBrief pipeline — 4 agents, one file.*

The brief should feel like it was written by someone who respects the reader's time
more than their own word count. Every sentence must survive the test: "would the
reader's decision change if I cut this?" If no, cut it."""


# ─── Internal persona classes (prefixed to hide from *Agent discovery) ──

class _InternalBriefScout(BasicAgent):
    def __init__(self):
        self.name = "BriefScout"
        self.metadata = {
            "name": self.name,
            "description": "Research analyst that gathers and structures intelligence on a business topic.",
            "parameters": {
                "type": "object",
                "properties": {
                    "topic": {
                        "type": "string",
                        "description": "The business topic or question to research"
                    },
                },
                "required": ["topic"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, topic="", **kwargs):
        if not topic.strip():
            return json.dumps({"status": "error", "message": "No topic provided"})
        prompt = (
            f"Research the following business topic and produce a structured "
            f"intelligence brief:\n\n"
            f"TOPIC: {topic}\n\n"
            f"Follow your output format exactly: SITUATION, LANDSCAPE, SIGNALS, GAPS."
        )
        result = _llm_call(_SOUL_BRIEF_SCOUT, prompt)
        return json.dumps({
            "status": "success",
            "research": result,
            "data_slush": {"topic": topic, "research_complete": True}
        })


class _InternalBriefAnalyst(BasicAgent):
    def __init__(self):
        self.name = "BriefAnalyst"
        self.metadata = {
            "name": self.name,
            "description": "Chief analyst that extracts insights, risks, and opportunities from structured research.",
            "parameters": {
                "type": "object",
                "properties": {
                    "research": {
                        "type": "string",
                        "description": "Structured research from the Scout agent"
                    },
                },
                "required": ["research"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, research="", **kwargs):
        if not research.strip():
            return json.dumps({"status": "error", "message": "No research provided"})
        prompt = (
            f"Analyze the following research and extract insights, risks, and "
            f"opportunities:\n\n"
            f"--- RESEARCH ---\n{research}\n--- END ---\n\n"
            f"Follow your output format exactly: KEY INSIGHTS, RISKS, OPPORTUNITIES, "
            f"TENSION MAP."
        )
        result = _llm_call(_SOUL_BRIEF_ANALYST, prompt)
        return json.dumps({
            "status": "success",
            "analysis": result,
            "data_slush": {"analysis_complete": True}
        })


class _InternalBriefStrategist(BasicAgent):
    def __init__(self):
        self.name = "BriefStrategist"
        self.metadata = {
            "name": self.name,
            "description": "VP of Strategy that turns analysis into 3 actionable recommendations with sequencing.",
            "parameters": {
                "type": "object",
                "properties": {
                    "analysis": {
                        "type": "string",
                        "description": "Analysis from the Analyst agent"
                    },
                    "topic": {
                        "type": "string",
                        "description": "Original topic for context"
                    },
                },
                "required": ["analysis"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, analysis="", topic="", **kwargs):
        if not analysis.strip():
            return json.dumps({"status": "error", "message": "No analysis provided"})
        topic_line = f"\nORIGINAL TOPIC: {topic}\n" if topic else ""
        prompt = (
            f"Based on the following analysis, produce strategic recommendations:"
            f"\n{topic_line}\n"
            f"--- ANALYSIS ---\n{analysis}\n--- END ---\n\n"
            f"Follow your output format exactly: STRATEGIC FRAME, RECOMMENDATIONS "
            f"(exactly 3), SEQUENCING, THE ASK."
        )
        result = _llm_call(_SOUL_BRIEF_STRATEGIST, prompt)
        return json.dumps({
            "status": "success",
            "strategy": result,
            "data_slush": {"strategy_complete": True}
        })


class _InternalBriefWriter(BasicAgent):
    def __init__(self):
        self.name = "BriefWriter"
        self.metadata = {
            "name": self.name,
            "description": "Executive communications director that composes a polished sub-400-word brief from pipeline inputs.",
            "parameters": {
                "type": "object",
                "properties": {
                    "topic": {
                        "type": "string",
                        "description": "The original business topic"
                    },
                    "research": {
                        "type": "string",
                        "description": "Structured research from the Scout"
                    },
                    "analysis": {
                        "type": "string",
                        "description": "Insights and risks from the Analyst"
                    },
                    "strategy": {
                        "type": "string",
                        "description": "Recommendations from the Strategist"
                    },
                },
                "required": ["strategy"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, topic="", research="", analysis="", strategy="", **kwargs):
        if not strategy.strip():
            return json.dumps({"status": "error", "message": "No strategy provided"})
        sections = []
        if topic:
            sections.append(f"TOPIC: {topic}")
        if research:
            sections.append(f"RESEARCH:\n{research}")
        if analysis:
            sections.append(f"ANALYSIS:\n{analysis}")
        sections.append(f"STRATEGY & RECOMMENDATIONS:\n{strategy}")
        prompt = (
            f"Compose a polished executive brief from the following pipeline outputs. "
            f"Follow your format exactly. Under 400 words. The brief must stand alone — "
            f"the reader has not seen the research, analysis, or strategy documents.\n\n"
            + "\n\n---\n\n".join(sections)
        )
        result = _llm_call(_SOUL_BRIEF_WRITER, prompt)
        return json.dumps({
            "status": "success",
            "brief": result,
            "data_slush": {"brief_complete": True}
        })


# ─── PUBLIC ENTRYPOINT ──────────────────────────────────────────────────

class ExecBrief(BasicAgent):
    def __init__(self):
        self.name = "ExecBrief"
        self.metadata = {
            "name": self.name,
            "description": (
                "Runs a four-agent pipeline (Scout, Analyst, Strategist, Writer) "
                "to produce a polished executive brief on any business topic. Use "
                "when the user wants an executive brief, strategic analysis, or "
                "leadership-ready summary on a topic."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "topic": {
                        "type": "string",
                        "description": "The business topic or question to brief on",
                    },
                },
                "required": ["topic"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, topic="", **kwargs):
        if not topic.strip():
            return json.dumps({"status": "error", "message": "No topic provided"})

        ws = os.path.join(
            os.environ.get("TWIN_WORKSPACE", "/tmp"), "exec-brief")
        os.makedirs(ws, exist_ok=True)

        def _save(name, content):
            with open(os.path.join(ws, name), "w") as f:
                f.write(content if isinstance(content, str) else str(content))

        def _extract(raw, key):
            try:
                parsed = json.loads(raw)
                return parsed.get(key, raw)
            except (json.JSONDecodeError, TypeError):
                return raw

        print(f'[ExecBrief] Starting pipeline: "{topic}"')

        # Live index card — one surface the UI polls for the whole run.
        # Each stage lights up as its agent works, then freezes into the
        # report. DeckForge only flips to "done" if it produced a URL.
        c = _card()
        c.start(
            title=f"Executive Brief: {topic}",
            subtitle="5-agent pipeline",
            stages=[
                ("scout",      "Scout"),
                ("analyst",    "Analyst"),
                ("strategist", "Strategist"),
                ("writer",     "Writer"),
                ("deckforge",  "DeckForge"),
            ],
        )

        c.stage("scout", status="running", note="gathering intelligence")
        print("[ExecBrief] Step 1/4: Scout gathering intelligence...")
        try:
            scout_raw = _InternalBriefScout().perform(topic=topic)
            _save("01-scout.md", scout_raw)
            research = _extract(scout_raw, "research")
            c.stage("scout", status="done", note="intelligence gathered")
        except Exception as e:
            c.stage("scout", status="failed", note=str(e)[:80])
            c.fail(f"Scout failed: {e}")
            raise

        c.stage("analyst", status="running", note="extracting insights")
        print("[ExecBrief] Step 2/4: Analyst extracting insights...")
        try:
            analyst_raw = _InternalBriefAnalyst().perform(research=research)
            _save("02-analyst.md", analyst_raw)
            analysis = _extract(analyst_raw, "analysis")
            c.stage("analyst", status="done", note="insights extracted")
        except Exception as e:
            c.stage("analyst", status="failed", note=str(e)[:80])
            c.fail(f"Analyst failed: {e}")
            raise

        c.stage("strategist", status="running", note="forming recommendations")
        print("[ExecBrief] Step 3/4: Strategist forming recommendations...")
        try:
            strategist_raw = _InternalBriefStrategist().perform(
                analysis=analysis, topic=topic)
            _save("03-strategist.md", strategist_raw)
            strategy = _extract(strategist_raw, "strategy")
            c.stage("strategist", status="done", note="recommendations formed")
        except Exception as e:
            c.stage("strategist", status="failed", note=str(e)[:80])
            c.fail(f"Strategist failed: {e}")
            raise

        c.stage("writer", status="running", note="composing brief")
        print("[ExecBrief] Step 4/4: Writer composing executive brief...")
        try:
            writer_raw = _InternalBriefWriter().perform(
                topic=topic, research=research,
                analysis=analysis, strategy=strategy)
            _save("04-brief.md", writer_raw)
            brief = _extract(writer_raw, "brief")
            c.stage("writer", status="done", note="brief ready")
        except Exception as e:
            c.stage("writer", status="failed", note=str(e)[:80])
            c.fail(f"Writer failed: {e}")
            raise

        # ── Step 5: DeckForge — turn the brief into a presentation ───────
        c.stage("deckforge", status="running", note="building pitch deck")
        print("[ExecBrief] Step 5/5: DeckForge building pitch deck...")
        deck = _build_pitch_deck(topic, brief, research, analysis, strategy, ws)
        if deck.get("url"):
            c.stage("deckforge", status="done", note="deck ready")
        else:
            c.stage("deckforge", status="failed", note="deck not built")

        print("[ExecBrief] Pipeline complete — 5 agents, 1 brief"
              + (", 1 deck." if deck.get("url") else "."))

        # Freeze the card into a report: artifacts + metrics, then finish.
        c.metric("agents", 5)
        c.metric("topic", topic)
        if deck.get("url"):
            c.metric("deck", deck["url"])
        c.artifact(
            kind="brief",
            title=f"Executive Brief: {topic}",
            body_md=brief if isinstance(brief, str) else json.dumps(brief, indent=2),
        )
        if deck.get("url"):
            c.artifact(
                kind="deck",
                title="Pitch deck",
                url=deck["url"],
                meta={"path": deck.get("path")},
            )
        c.finish()

        summary_parts = ["### Executive Brief", "", brief]
        if deck.get("url"):
            summary_parts += [
                "",
                "---",
                "",
                "### Presentation-ready pitch deck",
                "",
                f"**[Click to open your pitch deck in a new tab →]({deck['url']})**",
                "",
                "Light/dark theme (`T`) · Exec + rehearse modes (`R`) · "
                "Arrow keys or swipe to navigate. Rehearse mode adds the "
                "email draft, 3-minute video script, and run commands.",
            ]

        return json.dumps({
            "status": "success",
            "brief": brief,
            "deck_url": deck.get("url"),
            "deck_path": deck.get("path"),
            "pipeline": {
                "steps": 5,
                "agents": [
                    "BriefScout", "BriefAnalyst",
                    "BriefStrategist", "BriefWriter", "DeckForge",
                ],
            },
            "workspace": ws,
            "summary": "\n".join(summary_parts),
            "presentation_hint": (
                "Render the summary field verbatim to the user — keep the "
                "markdown link to the deck so the chat UI shows it as a "
                "clickable 'Open in new tab' button."
            ),
            "data_slush": {
                "topic": topic,
                "brief_ready": True,
                "deck_ready": bool(deck.get("url")),
                "deck_url": deck.get("url"),
            },
        })


class ExecBriefAgent(ExecBrief):
    pass


# ─── DeckForge: deliverable builder (optional — uses @rapp/pitch_deck) ───

def _build_pitch_deck(topic, brief, research, analysis, strategy, workspace):
    """Generate an HTML pitch deck and return {url, path} for the chat CTA.
    Relies on the optional @rapp/pitch_deck agent being present in the
    brainstem's agents/ dir. Skips silently if not."""
    web_dir = _find_brainstem_web_dir()
    slug = re.sub(r"[^a-z0-9]+", "-", (topic or "brief").lower()).strip("-")[:40] or "brief"
    filename = f"execbrief-{slug}-{int(time.time())}.html"
    if web_dir:
        pitches_dir = os.path.join(web_dir, "pitches")
        path = os.path.join(pitches_dir, filename)
        url = f"/web/pitches/{filename}"
    else:
        pitches_dir = workspace
        path = os.path.join(pitches_dir, filename)
        url = f"file://{path}"
    os.makedirs(pitches_dir, exist_ok=True)

    pitch_deck = _load_pitch_deck_agent()
    if pitch_deck is None:
        print("[DeckForge] @rapp/pitch_deck not installed — skipping deck")
        return {}

    try:
        thesis = (brief or "").strip()[:800]
        raw = pitch_deck.perform(
            topic=topic,
            thesis=thesis,
            audience="executive leadership",
            product_name=(topic.split(":")[0].strip() or "Executive Brief")[:40],
            output_path=path,
        )
        try:
            result = json.loads(raw) if isinstance(raw, str) else raw
        except (json.JSONDecodeError, TypeError):
            result = {}
        if result.get("status") == "success" and os.path.exists(path):
            return {"url": url, "path": path}
    except Exception as e:
        print(f"[DeckForge] generation failed: {e}")
    return {}


def _find_brainstem_web_dir():
    cur = os.path.dirname(os.path.abspath(__file__))
    for _ in range(6):
        candidate = os.path.join(cur, "web")
        if os.path.isdir(candidate) and any(
            os.path.exists(os.path.join(candidate, m))
            for m in ("onboard", "mobile", "index.html")
        ):
            return candidate
        parent = os.path.dirname(cur)
        if parent == cur:
            break
        cur = parent
    return None


def _load_pitch_deck_agent():
    candidates = []
    here = os.path.dirname(os.path.abspath(__file__))
    for rel in ("pitch_deck_agent.py", "../pitch_deck_agent.py"):
        candidates.append(os.path.normpath(os.path.join(here, rel)))
    web_dir = _find_brainstem_web_dir()
    if web_dir:
        candidates.append(os.path.join(os.path.dirname(web_dir), "agents", "pitch_deck_agent.py"))
    for p in candidates:
        if os.path.exists(p):
            try:
                spec = importlib.util.spec_from_file_location("pitch_deck_agent_dyn", p)
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)
                return mod.PitchDeckAgent()
            except Exception as e:
                print(f"[DeckForge] failed to load {p}: {e}")
                continue
    return None


# ─── Inlined LLM dispatch (one copy for the whole singleton) ────────────

def _llm_call(soul: str, user_prompt: str) -> str:
    messages = [{"role": "system", "content": soul},
                {"role": "user", "content": user_prompt}]

    endpoint = os.environ.get("AZURE_OPENAI_ENDPOINT", "")
    api_key = os.environ.get("AZURE_OPENAI_API_KEY", "")
    deployment = (os.environ.get("AZURE_OPENAI_DEPLOYMENT")
                  or os.environ.get("AZURE_OPENAI_DEPLOYMENT_NAME", ""))
    if endpoint and api_key:
        url = endpoint.rstrip("/")
        if "/chat/completions" not in url:
            url = f"{url}/openai/deployments/{deployment}/chat/completions?api-version=2025-01-01-preview"
        elif "?" not in url:
            url += "?api-version=2025-01-01-preview"
        return _post(url, {"messages": messages, "model": deployment},
                     {"Content-Type": "application/json", "api-key": api_key})

    if os.environ.get("OPENAI_API_KEY"):
        return _post("https://api.openai.com/v1/chat/completions",
                     {"model": os.environ.get("OPENAI_MODEL", "gpt-4o"),
                      "messages": messages},
                     {"Content-Type": "application/json",
                      "Authorization": "Bearer " + os.environ["OPENAI_API_KEY"]})

    import time as _time
    session_file = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        ".copilot_session")
    if os.path.exists(session_file):
        try:
            with open(session_file) as f:
                sess = json.load(f)
            if sess.get("token") and _time.time() < sess.get("expires_at", 0) - 60:
                return _post(
                    sess["endpoint"] + "/chat/completions",
                    {"model": os.environ.get("GITHUB_MODEL", "gpt-4o"),
                     "messages": messages},
                    {"Content-Type": "application/json",
                     "Authorization": "Bearer " + sess["token"],
                     "Editor-Version": "vscode/1.95.0",
                     "Copilot-Integration-Id": "vscode-chat"})
        except Exception:
            pass

    return "(no LLM configured — set AZURE_OPENAI_*, OPENAI_API_KEY, or start brainstem for Copilot)"


def _post(url, body, headers):
    req = urllib.request.Request(url, data=json.dumps(body).encode("utf-8"),
                                headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            j = json.loads(resp.read().decode("utf-8"))
        choices = j.get("choices") or []
        return (choices[0]["message"].get("content") or "") if choices else ""
    except urllib.error.HTTPError as e:
        return f"(LLM HTTP {e.code}: {e.read().decode('utf-8')[:200]})"
    except urllib.error.URLError as e:
        return f"(LLM network error: {e})"