"""
personalmemory_agent.py — A personal memory anchor for the user.

Agent-first: works through any LLM with no UI required.
The optional personalmemory_service.py exposes the same data over HTTP.

Storage: .brainstem_data/personalmemory.json
Auto-generated by VibeBuilder on 2026-05-24 03:39.
"""

import json
import uuid
import os
from datetime import datetime
from agents.basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/vibe_builder_agent",
    "version": "1.0.0",
    "display_name": "Personalmemory",
    "description": "A personal memory anchor for the user.",
    "author": "RAPP",
    "tags": ["memory", "anchors", "personal"],
    "category": "productivity",
    "quality_tier": "community",
    "requires_env": [],
    "example_call": "Save a memory anchor for my favorite childhood park",
}


def _data_path():
    return os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        ".brainstem_data", "personalmemory.json"
    )


def _read():
    path = _data_path()
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {"anchors": {}}


def _write(data):
    path = _data_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


class PersonalmemoryAgent(BasicAgent):
    def __init__(self):
        self.name = "Personalmemory"
        self.metadata = {
            "name": self.name,
            "description": (
                "A personal memory anchor for the user. Call this when the user wants to create, list, "
                "update, delete, or search memory_anchors."
            ),
            "parameters": {
            "type": "object",
            "properties": {
                        "action": {
                                    "type": "string",
                                    "enum": [
                                                "create",
                                                "list",
                                                "delete",
                                                "search"
                                    ],
                                    "description": "What to do."
                        },
                        "item_id": {
                                    "type": "string",
                                    "description": "Personalmemory ID (for update/delete). Use 'list' to find IDs."
                        },
                        "title": {
                                    "type": "string",
                                    "description": "A short title for the memory anchor"
                        },
                        "description": {
                                    "type": "string",
                                    "description": "A detailed description of the memory"
                        },
                        "timestamp": {
                                    "type": "string",
                                    "description": "A date or time associated with the memory"
                        },
                        "tags": {
                                    "type": "array",
                                    "description": "Tags to organize or search memories"
                        }
            },
            "required": [
                        "action"
            ]
},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        action = kwargs.get("action", "list")
        data = _read()

        if action == "create":
            title = kwargs.get("title", "")
            description = kwargs.get("description", "")
            timestamp = kwargs.get("timestamp", "")
            tags = kwargs.get("tags", "")
            tid = str(uuid.uuid4())[:8]
            data["anchors"][tid] = {
                "title": title,
                "description": description,
                "timestamp": timestamp,
                "tags": tags,
                "created": datetime.now().strftime("%Y-%m-%d %H:%M"),
            }
            _write(data)
            return json.dumps({
                "status": "ok",
                "summary": f'Created personalmemory "{kwargs.get("title", tid)}" (ID: {tid})',
                "item_id": tid,
            })

        if action == "list":
            items = data["anchors"]
            if not items:
                return json.dumps({"status": "ok", "summary": "No memory_anchors yet.", "anchors": {}})
            lines = []
            for tid, t in items.items():
                line = f"  - [{tid}] {t.get('title', '')} | {t.get('description', '')} | {t.get('timestamp', '')}"
                lines.append(line)
            return json.dumps({
                "status": "ok",
                "summary": f"{len(items)} memory_anchors:\n" + "\n".join(lines),
                "anchors": items,
            })

        if action == "delete":
            tid = kwargs.get("item_id", "")
            if tid not in data["anchors"]:
                return json.dumps({"status": "error", "summary": f"Personalmemory {tid} not found."})
            removed = data["anchors"].pop(tid)
            _write(data)
            label = removed.get('title', tid)
            return json.dumps({"status": "ok", "summary": f'Deleted personalmemory "{label}"'})

        if action == "search":
            query = " ".join(str(v) for v in kwargs.values() if v and v != "search").lower()
            matches = {}
            for tid, t in data["anchors"].items():
                hay = json.dumps(t).lower()
                if query in hay:
                    matches[tid] = t
            if not matches:
                return json.dumps({"status": "ok", "summary": f"No memory_anchors match '{query}'."})
            lines = [f"  - [{tid}] {json.dumps(t)}" for tid, t in matches.items()]
            return json.dumps({"status": "ok", "summary": f"{len(matches)} match(es):\n" + "\n".join(lines)})

        return json.dumps({"status": "error", "summary": f"Unknown action: {action}"})
