"""
task_agent.py — A task manager to keep you organized.

Agent-first: works through any LLM with no UI required.
The optional task_service.py exposes the same data over HTTP.

Storage: .brainstem_data/task.json
Auto-generated by VibeBuilder on 2026-05-24 03:41.
"""

import json
import uuid
import os
from datetime import datetime
from agents.basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/vibe_builder_agent",
    "version": "1.0.0",
    "display_name": "Task",
    "description": "A task manager to keep you organized.",
    "author": "RAPP",
    "tags": ["tasks", "todo", "organization"],
    "category": "productivity",
    "quality_tier": "community",
    "requires_env": [],
    "example_call": "Create a task to buy groceries",
}


def _data_path():
    return os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        ".brainstem_data", "task.json"
    )


def _read():
    path = _data_path()
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {"tasks": {}}


def _write(data):
    path = _data_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


class TaskAgent(BasicAgent):
    def __init__(self):
        self.name = "Task"
        self.metadata = {
            "name": self.name,
            "description": (
                "A task manager to keep you organized. Call this when the user wants to create, list, "
                "update, delete, or search tasks."
            ),
            "parameters": {
            "type": "object",
            "properties": {
                        "action": {
                                    "type": "string",
                                    "enum": [
                                                "create",
                                                "list",
                                                "delete",
                                                "update",
                                                "search"
                                    ],
                                    "description": "What to do."
                        },
                        "item_id": {
                                    "type": "string",
                                    "description": "Task ID (for update/delete). Use 'list' to find IDs."
                        },
                        "title": {
                                    "type": "string",
                                    "description": "The title of the task"
                        },
                        "description": {
                                    "type": "string",
                                    "description": "Details about the task"
                        },
                        "due_date": {
                                    "type": "string",
                                    "description": "Deadline for the task in ISO format"
                        },
                        "completed": {
                                    "type": "boolean",
                                    "description": "Whether the task is completed"
                        }
            },
            "required": [
                        "action"
            ]
},
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        action = kwargs.get("action", "list")
        data = _read()

        if action == "create":
            title = kwargs.get("title", "")
            description = kwargs.get("description", "")
            due_date = kwargs.get("due_date", "")
            completed = kwargs.get("completed", "")
            tid = str(uuid.uuid4())[:8]
            data["tasks"][tid] = {
                "title": title,
                "description": description,
                "due_date": due_date,
                "completed": completed,
                "created": datetime.now().strftime("%Y-%m-%d %H:%M"),
            }
            _write(data)
            return json.dumps({
                "status": "ok",
                "summary": f'Created task "{kwargs.get("title", tid)}" (ID: {tid})',
                "item_id": tid,
            })

        if action == "list":
            items = data["tasks"]
            if not items:
                return json.dumps({"status": "ok", "summary": "No tasks yet.", "tasks": {}})
            lines = []
            for tid, t in items.items():
                line = f"  - [{tid}] {t.get('title', '')} | {t.get('description', '')} | {t.get('due_date', '')}"
                lines.append(line)
            return json.dumps({
                "status": "ok",
                "summary": f"{len(items)} tasks:\n" + "\n".join(lines),
                "tasks": items,
            })

        if action == "update":
            tid = kwargs.get("item_id", "")
            if tid not in data["tasks"]:
                return json.dumps({"status": "error", "summary": f"Task {tid} not found."})
            if kwargs.get("title"): data["tasks"][tid]["title"] = kwargs["title"]
            if kwargs.get("description"): data["tasks"][tid]["description"] = kwargs["description"]
            if kwargs.get("due_date"): data["tasks"][tid]["due_date"] = kwargs["due_date"]
            if kwargs.get("completed"): data["tasks"][tid]["completed"] = kwargs["completed"]
            _write(data)
            return json.dumps({"status": "ok", "summary": f"Updated task {tid}"})

        if action == "delete":
            tid = kwargs.get("item_id", "")
            if tid not in data["tasks"]:
                return json.dumps({"status": "error", "summary": f"Task {tid} not found."})
            removed = data["tasks"].pop(tid)
            _write(data)
            label = removed.get('title', tid)
            return json.dumps({"status": "ok", "summary": f'Deleted task "{label}"'})

        if action == "search":
            query = " ".join(str(v) for v in kwargs.values() if v and v != "search").lower()
            matches = {}
            for tid, t in data["tasks"].items():
                hay = json.dumps(t).lower()
                if query in hay:
                    matches[tid] = t
            if not matches:
                return json.dumps({"status": "ok", "summary": f"No tasks match '{query}'."})
            lines = [f"  - [{tid}] {json.dumps(t)}" for tid, t in matches.items()]
            return json.dumps({"status": "ok", "summary": f"{len(matches)} match(es):\n" + "\n".join(lines)})

        return json.dumps({"status": "error", "summary": f"Unknown action: {action}"})
