"""
personalmemory_service.py — Optional HTTP layer for the Personalmemory rapplication.

Reads/writes the same .brainstem_data/personalmemory.json that
personalmemory_agent.py uses. The agent works without this service.
Auto-generated by VibeBuilder on 2026-05-24 03:39.
"""

import json
import os
import uuid
from datetime import datetime

name = "personalmemory"

_DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".brainstem_data")
_STATE_FILE = os.path.join(_DATA_DIR, "personalmemory.json")


def _read():
    if os.path.exists(_STATE_FILE):
        with open(_STATE_FILE) as f:
            return json.load(f)
    return {"anchors": {}}


def _write(data):
    os.makedirs(_DATA_DIR, exist_ok=True)
    with open(_STATE_FILE, "w") as f:
        json.dump(data, f, indent=2)


def handle(method, path, body):
    data = _read()

    # GET /api/personalmemory — list all
    if method == "GET" and path == "":
        return data, 200

    # POST /api/personalmemory/items — create
    if method == "POST" and path == "items":
        tid = str(uuid.uuid4())[:8]
        item = {k: body.get(k, "") for k in ["title", "description", "timestamp", "tags"]}
        item["created"] = datetime.now().strftime("%Y-%m-%d %H:%M")
        data["anchors"][tid] = item
        _write(data)
        return {"status": "ok", "id": tid}, 201

    # PUT /api/personalmemory/items/<id> — update
    if method == "PUT" and path.startswith("items/"):
        tid = path[len("items/"):]
        if tid not in data["anchors"]:
            return {"error": "not found"}, 404
        item = data["anchors"][tid]
        if "title" in body: item["title"] = body["title"]
        if "description" in body: item["description"] = body["description"]
        if "timestamp" in body: item["timestamp"] = body["timestamp"]
        if "tags" in body: item["tags"] = body["tags"]
        _write(data)
        return {"status": "ok", "item": item}, 200

    # DELETE /api/personalmemory/items/<id> — delete
    if method == "DELETE" and path.startswith("items/"):
        tid = path[len("items/"):]
        if tid not in data["anchors"]:
            return {"error": "not found"}, 404
        data["anchors"].pop(tid)
        _write(data)
        return {"status": "ok"}, 200

    return {"error": "not found"}, 404
