"""
task_service.py — Optional HTTP layer for the Task rapplication.

Reads/writes the same .brainstem_data/task.json that
task_agent.py uses. The agent works without this service.
Auto-generated by VibeBuilder on 2026-05-24 03:41.
"""

import json
import os
import uuid
from datetime import datetime

name = "task"

_DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".brainstem_data")
_STATE_FILE = os.path.join(_DATA_DIR, "task.json")


def _read():
    if os.path.exists(_STATE_FILE):
        with open(_STATE_FILE) as f:
            return json.load(f)
    return {"tasks": {}}


def _write(data):
    os.makedirs(_DATA_DIR, exist_ok=True)
    with open(_STATE_FILE, "w") as f:
        json.dump(data, f, indent=2)


def handle(method, path, body):
    data = _read()

    # GET /api/task — list all
    if method == "GET" and path == "":
        return data, 200

    # POST /api/task/items — create
    if method == "POST" and path == "items":
        tid = str(uuid.uuid4())[:8]
        item = {k: body.get(k, "") for k in ["title", "description", "due_date", "completed"]}
        item["created"] = datetime.now().strftime("%Y-%m-%d %H:%M")
        data["tasks"][tid] = item
        _write(data)
        return {"status": "ok", "id": tid}, 201

    # PUT /api/task/items/<id> — update
    if method == "PUT" and path.startswith("items/"):
        tid = path[len("items/"):]
        if tid not in data["tasks"]:
            return {"error": "not found"}, 404
        item = data["tasks"][tid]
        if "title" in body: item["title"] = body["title"]
        if "description" in body: item["description"] = body["description"]
        if "due_date" in body: item["due_date"] = body["due_date"]
        if "completed" in body: item["completed"] = body["completed"]
        _write(data)
        return {"status": "ok", "item": item}, 200

    # DELETE /api/task/items/<id> — delete
    if method == "DELETE" and path.startswith("items/"):
        tid = path[len("items/"):]
        if tid not in data["tasks"]:
            return {"error": "not found"}, 404
        data["tasks"].pop(tid)
        _write(data)
        return {"status": "ok"}, 200

    return {"error": "not found"}, 404
